//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sensors_with_entity_framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sensors()
        {
            this.SensorReadings = new HashSet<SensorReadings>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdSensorTypes { get; set; }
        public Nullable<int> IdMeasurementUnits { get; set; }
    
        public virtual MeasurementUnits MeasurementUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SensorReadings> SensorReadings { get; set; }
        public virtual SensorTypes SensorTypes { get; set; }
    }
}
